export const GLOBAL_ITEM_TEMPLATES = [
  // 1. Branding anchor
  { item_name: 'Toilet Paper', default_unit: 'packages'},

  // 2–20. Household essentials
  { item_name: 'Paper Towels', default_unit: 'packages'},
  { item_name: 'Trash Bags', default_unit: 'boxes'},
  { item_name: 'Laundry Detergent', default_unit: 'bottles'},
  { item_name: 'Fabric Softener', default_unit: 'bottles'},
  { item_name: 'Dish Soap', default_unit: 'bottles'},
  { item_name: 'Sponges', default_unit: 'packs'},
  { item_name: 'All-Purpose Cleaner', default_unit: 'bottles'},
  { item_name: 'Disinfecting Wipes', default_unit: 'canisters'},
  { item_name: 'Hand Soap', default_unit: 'bottles'},
  { item_name: 'Shampoo', default_unit: 'bottles'},
  { item_name: 'Conditioner', default_unit: 'bottles'},
  { item_name: 'Body Wash', default_unit: 'bottles'},
  { item_name: 'Toothpaste', default_unit: 'tubes'},
  { item_name: 'Toothbrush', default_unit: 'units'},
  { item_name: 'Deodorant', default_unit: 'sticks'},
  { item_name: 'Shaving Cream', default_unit: 'cans'},
  { item_name: 'Razor Blades', default_unit: 'packs'},
  { item_name: 'Cotton Swabs', default_unit: 'boxes'},
  { item_name: 'Facial Tissue', default_unit: 'boxes'},

  // 21–40. Pantry staples and cereals
  { item_name: 'Eggs', default_unit: 'dozen'},
  { item_name: 'Milk', default_unit: 'gallons'},
  { item_name: 'Butter', default_unit: 'sticks'},
  { item_name: 'Cheese', default_unit: 'blocks'},
  { item_name: 'Yogurt', default_unit: 'cups'},
  { item_name: 'Cereal', default_unit: 'boxes'},
  { item_name: 'Oatmeal', default_unit: 'containers'},
  { item_name: 'Bread', default_unit: 'loaves'},
  { item_name: 'Bagels', default_unit: 'packs'},
  { item_name: 'Rice', default_unit: 'pounds'},
  { item_name: 'Pasta', default_unit: 'boxes'},
  { item_name: 'Flour', default_unit: 'bags'},
  { item_name: 'Sugar', default_unit: 'bags'},
  { item_name: 'Salt', default_unit: 'containers'},
  { item_name: 'Black Pepper', default_unit: 'containers'},
  { item_name: 'Cooking Oil', default_unit: 'bottles'},
  { item_name: 'Olive Oil', default_unit: 'bottles'},
  { item_name: 'Vinegar', default_unit: 'bottles'},
  { item_name: 'Tomato Sauce', default_unit: 'jars'},
  { item_name: 'Canned Soup', default_unit: 'cans'},

  // 41–60. Protein and fresh foods
  { item_name: 'Chicken Breast', default_unit: 'pounds'},
  { item_name: 'Ground Beef', default_unit: 'pounds'},
  { item_name: 'Pork Chops', default_unit: 'pounds'},
  { item_name: 'Bacon', default_unit: 'packs'},
  { item_name: 'Fish Fillets', default_unit: 'pounds'},
  { item_name: 'Shrimp', default_unit: 'pounds'},
  { item_name: 'Apples', default_unit: 'pounds'},
  { item_name: 'Bananas', default_unit: 'bunches'},
  { item_name: 'Oranges', default_unit: 'pounds'},
  { item_name: 'Grapes', default_unit: 'pounds'},
  { item_name: 'Strawberries', default_unit: 'pints'},
  { item_name: 'Blueberries', default_unit: 'pints'},
  { item_name: 'Lettuce', default_unit: 'heads'},
  { item_name: 'Spinach', default_unit: 'bags'},
  { item_name: 'Broccoli', default_unit: 'crowns'},
  { item_name: 'Carrots', default_unit: 'pounds'},
  { item_name: 'Potatoes', default_unit: 'pounds'},
  { item_name: 'Onions', default_unit: 'pounds'},
  { item_name: 'Garlic', default_unit: 'bulbs'},
  { item_name: 'Tomatoes', default_unit: 'pounds'},

  // 61–75. Health and functional foods
  { item_name: 'Protein Powder', default_unit: 'containers'},
  { item_name: 'Protein Bars', default_unit: 'boxes'},
  { item_name: 'Vitamins', default_unit: 'bottles'},
  { item_name: 'Supplements', default_unit: 'bottles'},
  { item_name: 'Kombucha', default_unit: 'bottles'},
  { item_name: 'Probiotic Soda', default_unit: 'cans'},
  { item_name: 'Functional Juice Shots', default_unit: 'bottles'},
  { item_name: 'Overnight Oats', default_unit: 'cups'},
  { item_name: 'Plant-Based Milk', default_unit: 'cartons'},
  { item_name: 'Plant-Based Burgers', default_unit: 'packs'},
  { item_name: 'Tofu', default_unit: 'blocks'},
  { item_name: 'Tempeh', default_unit: 'blocks'},
  { item_name: 'Nut Butter', default_unit: 'jars'},
  { item_name: 'Almonds', default_unit: 'bags'},
  { item_name: 'Granola', default_unit: 'bags'},

  // 76–90. Snacks, drinks, and convenience
  { item_name: 'Chips', default_unit: 'bags'},
  { item_name: 'Popcorn', default_unit: 'bags'},
  { item_name: 'Crackers', default_unit: 'boxes'},
  { item_name: 'Cookies', default_unit: 'packs'},
  { item_name: 'Candy', default_unit: 'bags'},
  { item_name: 'Granola Bars', default_unit: 'boxes'},
  { item_name: 'Instant Noodles', default_unit: 'packs'},
  { item_name: 'Frozen Pizza', default_unit: 'boxes'},
  { item_name: 'Frozen Vegetables', default_unit: 'bags'},
  { item_name: 'Frozen Fruit', default_unit: 'bags'},
  { item_name: 'Ready-to-Eat Meals', default_unit: 'packages'},
  { item_name: 'Sushi (Ready-to-Eat)', default_unit: 'trays'},
  { item_name: 'Coffee', default_unit: 'bags'},
  { item_name: 'Tea', default_unit: 'boxes'},
  { item_name: 'Sparkling Water', default_unit: 'cans'},
  { item_name: 'Bottled Water', default_unit: 'bottles'},

  // 91–100. Miscellaneous and household goods
  { item_name: 'Paper Plates', default_unit: 'packs'},
  { item_name: 'Plastic Cutlery', default_unit: 'packs'},
  { item_name: 'Napkins', default_unit: 'packs'},
  { item_name: 'Aluminum Foil', default_unit: 'rolls'},
  { item_name: 'Plastic Wrap', default_unit: 'rolls'},
  { item_name: 'Zipper Bags', default_unit: 'boxes'},
  { item_name: 'Reusable Bags', default_unit: 'units'},
  { item_name: 'Cleaning Spray', default_unit: 'bottles'},
  { item_name: 'Broom', default_unit: 'units'},
  { item_name: 'Mop', default_unit: 'units'},
];